import taping from "../Images/Taping-therapy.jpg";
import DRY from "../Images/Dry-Needling.jpeg";
import IASTM from "../Images/IASTM.jpg";
import CUPPING from "../Images/Cupping.webp";

const coursesData = [
    { id: 'taping', title: 'TAPING', image: taping, description: 'The Taping Therapy course is a comprehensive and specialized health-related program that focuses on the principles, techniques, and applications of therapeutic taping in the context of modern healthcare. This course provides students with a deep understanding of the various taping methods, such as kinesiology taping and athletic taping, and their roles in injury prevention, rehabilitation, and performance enhancement. Participants will explore the physiological effects of taping on muscles, joints, and soft tissues, gaining valuable insights into how this therapeutic modality can be integrated into diverse healthcare practices.' },
    { id: 'dry-needling', title: 'DRY NEEDLING', image: DRY, description: 'The Dry Needling Therapy course is a specialized and dynamic program designed to provide healthcare professionals with a comprehensive understanding of the principles, techniques, and applications of dry needling in the realm of modern healthcare. This course delves into the theoretical foundations of dry needling, exploring its origins, underlying neurophysiological mechanisms, and evidence-based practices. Participants will gain insight into the integration of dry needling as a therapeutic intervention for musculoskeletal conditions, pain management, and functional improvement.' },
    { id: 'iastm', title: 'IASTM', image: IASTM, description: 'IASTM uses a bevel edge instrument, which adds shearing stress to soft tissue to facilitate and enhance the body’s healing response. The ability to focus a technical force along a small contact surface to your patient’s target tissue, and do so with a relatively high level of comfort for both the patient and treating therapist is one of the best features of this technique.' },
    { id: 'cupping', title: 'CUPPING', image: CUPPING,description: 'The Cupping Therapy course is a specialized health-related program that provides in-depth insights into the ancient practice of cupping and its contemporary applications in healthcare. Students will embark on a journey to understand the historical origins and cultural significance of cupping therapy, exploring its integration into various traditional healing systems. The curriculum will cover the diverse methods of cupping, ranging from dry cupping techniques to the more intricate wet cupping or Hijama, ensuring a comprehensive understanding of this therapeutic modality.' },
  ];
  
  export default coursesData;
  